fix: the stored last n headers is less than expected
nervosnetwork/ckb-light-client pull request #121
Opened 2023-01-10 21:42 UTC by yangby-cryptape

# Features

- When add proved blocks, if the count of new last N headers is not equal to or greater than the expected count of the last N blocks, just copy some old last N headers to make sure we have enough stored last N headers.

- Refactor unit tests to make it easier to add an `assert` to several unit tests, not just copy the code several times.

  And also add more unit tests to improve the coverage.

Resolve #117.

2023-01-10 23:02 UTC, yangby-cryptape commented on src/tests/protocols/light_client/send_last_state_proof.rs
> +        assert_eq!(
The checks for the stored last N headers in unit tests.

2023-01-10 23:02 UTC, yangby-cryptape commented on src/tests/protocols/light_client/send_last_state_proof.rs
> +        assert_eq!(
The checks for the stored last N headers in unit tests.

2023-01-11 05:08 UTC, quake requested changes

2023-01-11 05:08 UTC, quake commented on src/protocols/light_client/components/send_last_state_proof.rs
> +                                .iter()
suggest to use `iterator#skip`

```suggestion
                            old_last_headers
                                .iter()
                                .skip(old_last_headers_len.saturating_sub(required_count))
```

2023-01-11 08:30 UTC, yangby-cryptape commented on src/protocols/light_client/components/send_last_state_proof.rs
> +                        // iff the chain only has 1 block after MMR enabled.
Common abbreviation of "if and only if".

2023-01-11 10:57 UTC, quake approved these changes

2023-01-11 10:57 UTC, merged