feat: wasm support for browser
nervosnetwork/ckb-light-client pull request #204
Opened 2024-12-01 13:13 UTC by Officeyutong

**WORK IN PROGRESS, NOT TO BE REVIEWED/MERGED NOW**

This PR adds support for running light client in browser, including the following major changes:
- Split `light-client` into `light-client-lib`, `light-client-bin`, and `light-client-wasm`
- Uses IndexedDB in browser instead of RocksDB
- Adds `light-client-db-worker` to provide sync API access for IndexedDB
- Adds `light-client-js` as a JS API wrapper for frontend developers, with type definition from `@ckb-ccc/core` and similar APIs like RPC client
- Adds webpack configuration for `light-client-wasm`, `light-client-db-worker` and `light-client-js`, making them easy to be published to registries like npm

Things need to be done:
- Waiting for a bug in `@ckb-ccc/core` https://github.com/ckb-devrel/ccc/pull/90 to be fixed
- Most types we used from `@ckb-ccc/core` are not exposed by default. Need more communication with devrel to discuss if these should be exposed
- Integrated tests and unit-tests

2024-12-03 07:53 UTC, Hanssen0 commented
CCC fix released in https://github.com/ckb-devrel/ccc/pull/93

2024-12-03 09:09 UTC, Officeyutong commented
(Mis-clicked to close, please ignore that)

2024-12-03 09:12 UTC, Hanssen0 commented
> > CCC fix released in [ckb-devrel/ccc#93](https://github.com/ckb-devrel/ccc/pull/93)
> 
> But I didn't find any changes related to code in this PR, seems something was forgotten

https://github.com/ckb-devrel/ccc/pull/92 is the fix, and https://github.com/ckb-devrel/ccc/pull/93 is the release of the fix.

2024-12-03 09:18 UTC, Officeyutong commented
> > > CCC fix released in [ckb-devrel/ccc#93](https://github.com/ckb-devrel/ccc/pull/93)
> > 
> > 
> > But I didn't find any changes related to code in this PR, seems something was forgotten
> 
> [ckb-devrel/ccc#92](https://github.com/ckb-devrel/ccc/pull/92) is the fix, and [ckb-devrel/ccc#93](https://github.com/ckb-devrel/ccc/pull/93) is the release of the fix. The fix was included in the changelog.

I found it just now, thank you!

2025-01-09 06:07 UTC, eval-exec commented on light-client-lib/src/storage/db/browser.rs
> +    prelude::{Entity, FromSliceShouldBeOk, IntoBlockView, Pack, PackVec},
Suggest merge these import statements

2025-01-09 06:13 UTC, eval-exec commented on wasm/light-client-db-worker/src/tests.rs
It's empty.

2025-01-09 08:48 UTC, Officeyutong commented on wasm/light-client-db-worker/src/tests.rs
Removed now

2025-01-09 08:48 UTC, Officeyutong commented on light-client-lib/src/storage/db/browser.rs
> +    prelude::{Entity, FromSliceShouldBeOk, IntoBlockView, Pack, PackVec},
Fixed

2025-01-16 08:08 UTC, chaoticlonghair commented on light-client-lib/src/storage/mod.rs
> +    pending_txs: Arc<std::sync::RwLock<PendingTxs>>,
Just a suggestion:

- Use the keyword `type` to make an alias for `tokio::sync::RwLock` and `std::sync::RwLock`.

  For example,

  ```rust
  #[cfg(target_arch = "wasm32")]
  pub type YOUR_NAMED_RwLock = tokio::sync::RwLock;
  #[cfg(not(target_arch = "wasm32"))]
  pub type YOUR_NAMED_RwLock = std::sync::RwLock;
  ```

- Then, lots of lines could be removed.

  For example, the following two functions could be merged into one.

  ```rust
  impl StorageWithChainData {                                                                                              
      #[cfg(target_arch = "wasm32")]                                                                                       
      pub fn new(                                                                                                          
          storage: Storage,                                                                                                
          peers: Arc<Peers>,                                                                                               
          pending_txs: Arc<tokio::sync::RwLock<PendingTxs>>,                                                                  
      ) -> Self {                                                                                                          
          Self {                                                                                                           
              storage,                                                                                                     
              peers,                                                                                                       
              pending_txs,                                                                                                 
          }                                                                                                                
      }                                                                                                                    
      #[cfg(not(target_arch = "wasm32"))]                                                                                  
      pub fn new(                                                                                                          
          storage: Storage,                                                                                                
          peers: Arc<Peers>,                                                                                               
          pending_txs: Arc<std::sync::RwLock<PendingTxs>>,                                                                 
      ) -> Self {                                                                                                          
          Self {                                                                                                           
              storage,                                                                                                     
              peers,                                                                                                       
              pending_txs,                                                                                                 
          }                                                                                                                
      }
  }
  ```

2025-01-16 08:08 UTC, chaoticlonghair commented on light-client-lib/src/storage/mod.rs
> +}
If I was correct, this implementation is just as the same as the above (the implementation for `is(wasm32)`).

Some implementations, (e.g. `HeaderProvider`, `HeaderFiledsProvider`) could be removed when they has the same code in different architectures (`is(wasm32)` and `not(wasm32)`).

p.s. `Bytes32` is `packed::Bytes32`.

2025-01-16 08:54 UTC, chaoticlonghair requested changes
Add `rustup target add wasm32-unknown-unknown` to the CI workflows to fix CI errors.

2025-01-16 17:20 UTC, Officeyutong commented on light-client-lib/src/storage/mod.rs
> +}
`HeaderProvider`, `ExtensionProvider` and `HeaderFieldsProvider` are deduplicated now

2025-01-16 17:57 UTC, Officeyutong commented on light-client-lib/src/storage/mod.rs
> +    pending_txs: Arc<std::sync::RwLock<PendingTxs>>,
Added `light_client_lib::types::GeneralRwLock` and `light_client_lib::types::GeneralMutex` now

2025-01-17 00:09 UTC, chaoticlonghair submitted a review, later dismissed
Rust part LGTM.

2025-01-17 01:50 UTC, quake commented on light-client-bin/.gitignore
> +/Cargo.lock
as an application, we should check-in Cargo.lock

2025-01-17 01:50 UTC, quake commented on light-client-lib/src/protocols/filter/block_filter.rs
> +use crate::types::GeneralRwLock;
suggest to use the same name with std: `crate::types::RwLock`

2025-01-17 01:50 UTC, quake commented on light-client-lib/src/protocols/filter/block_filter.rs
> +                // Status::ok()
please cleanup code

2025-01-17 01:50 UTC, quake commented on light-client-lib/src/protocols/filter/block_filter.rs
> +                // Status::ok()
please cleanup code

2025-01-17 01:50 UTC, quake commented on wasm/light-client-js/README.md
> +listen_address = "127.0.0.1:9000"
do we need rpc listen port for wasm?

2025-01-17 01:54 UTC, Officeyutong commented on light-client-bin/.gitignore
> +/Cargo.lock
Actual `Cargo.lock` is located at the root of this project

2025-01-17 01:56 UTC, Officeyutong commented on light-client-lib/src/protocols/filter/block_filter.rs
> +                // Status::ok()
Removed that comment now

2025-01-17 01:56 UTC, Officeyutong commented on light-client-lib/src/protocols/filter/block_filter.rs
> +                // Status::ok()
Removed that comment now

2025-01-17 02:30 UTC, Officeyutong commented on light-client-lib/src/protocols/filter/block_filter.rs
> +use crate::types::GeneralRwLock;
Renamed now

2025-01-17 02:32 UTC, Officeyutong commented on wasm/light-client-js/README.md
> +listen_address = "127.0.0.1:9000"
It's not needed, updated this README now

2025-01-18 09:45 UTC, chaoticlonghair approved these changes

2025-01-21 03:50 UTC, merged